### ISSUE TITLE
FrogJump renamed to FrogLump w/ ActiveState P.D.K. Binaries

### ISSUE THREAD

**Issue by jmcveigh** [tadegenban/Games-FrogJump#2]
Hi:

I renamed FrogJump to FrogLump as FrogJump denotes a classic retro Frogger clone.

I've added the ActiveState P.D.K. Binaries for Microsoft Windows 64.
I've added the ActiveState P.D.K. Binaries for Mac OSX 32.

You're welcome to merge back or comment on my Fork.

**Comment by tadegenban** [comment]
nice work, have fun :)
